export const SCHEMES = {
  SCHEME_2019: '2019',
  SCHEME_2024: '2024'
};

export const ENTRY_TYPES = {
  REGULAR: 'regular',
  LATERAL: 'lateral'
};

export const PROCESSING_STATUS = {
  PROCESSING: 'PROCESSING',
  COUNTED: 'COUNTED',
  NOT_ELIGIBLE: 'NOT_ELIGIBLE',
  INSUFFICIENT_EVIDENCE: 'INSUFFICIENT_EVIDENCE',
  INSUFFICIENT_RULE_DATA: 'INSUFFICIENT_RULE_DATA',
  DUPLICATE: 'DUPLICATE',
  FAILED: 'FAILED'
};

export const RULE_EVALUATION_STATUS = {
  ELIGIBLE: 'ELIGIBLE',
  NOT_ELIGIBLE: 'NOT_ELIGIBLE',
  INSUFFICIENT_RULE_DATA: 'INSUFFICIENT_RULE_DATA',
  CAP_REACHED: 'CAP_REACHED',
  DUPLICATE: 'DUPLICATE'
};

export const CONFIDENCE_THRESHOLDS = {
  HIGH: 0.85,
  ACCEPTABLE: 0.70,
  MINIMUM: 0.60
};

export const ALLOWED_MIME_TYPES = [
  'application/pdf',
  'image/png',
  'image/jpeg',
  'image/jpg'
];

export const MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024; // 10MB

export const EVIDENCE_STATUS = {
  VALID_EVIDENCE: 'VALID_EVIDENCE',
  INVALID_EVIDENCE: 'INVALID_EVIDENCE',
  INSUFFICIENT_EVIDENCE: 'INSUFFICIENT_EVIDENCE'
};

export const REASON_CODES = {
  // Valid
  VERIFIED_ACTIVITY_EVIDENCE: 'VERIFIED_ACTIVITY_EVIDENCE',

  // Invalid Evidence
  PROMOTIONAL_MATERIAL: 'PROMOTIONAL_MATERIAL',
  CAMPAIGN_MATERIAL: 'CAMPAIGN_MATERIAL',
  PRE_EVENT_DOCUMENT: 'PRE_EVENT_DOCUMENT',
  SCHEDULE_OR_TIMETABLE: 'SCHEDULE_OR_TIMETABLE',
  ACADEMIC_NOTES: 'ACADEMIC_NOTES',
  ID_OR_MEMBERSHIP_CARD: 'ID_OR_MEMBERSHIP_CARD',
  CERTIFICATE_TEMPLATE: 'CERTIFICATE_TEMPLATE',
  STUDENT_MISMATCH: 'STUDENT_MISMATCH',
  UNRELATED_DOCUMENT: 'UNRELATED_DOCUMENT',
  NO_COMPLETED_ACTIVITY_EVIDENCE: 'NO_COMPLETED_ACTIVITY_EVIDENCE',

  // Insufficient Evidence
  BLURRY_OR_LOW_QUALITY: 'BLURRY_OR_LOW_QUALITY',
  MISSING_RECIPIENT_IDENTITY: 'MISSING_RECIPIENT_IDENTITY',
  AMBIGUOUS_DOCUMENT_PURPOSE: 'AMBIGUOUS_DOCUMENT_PURPOSE',
  INCOMPLETE_DOCUMENT_TEXT: 'INCOMPLETE_DOCUMENT_TEXT',

  // Technical Failures
  TEXT_EXTRACTION_FAILED: 'TEXT_EXTRACTION_FAILED',
  PROCESSING_FAILED: 'PROCESSING_FAILED',
  STORAGE_FAILED: 'STORAGE_FAILED',
  AI_ANALYSIS_FAILED: 'AI_ANALYSIS_FAILED'
};

export const DOCUMENT_PURPOSES = {
  // Completed activity proof
  PARTICIPATION_CERTIFICATE: 'PARTICIPATION_CERTIFICATE',
  COMPLETION_CERTIFICATE: 'COMPLETION_CERTIFICATE',
  ACHIEVEMENT_CERTIFICATE: 'ACHIEVEMENT_CERTIFICATE',
  MERIT_CERTIFICATE: 'MERIT_CERTIFICATE',
  APPRECIATION_CERTIFICATE: 'APPRECIATION_CERTIFICATE',
  OFFICIAL_ACTIVITY_EVIDENCE: 'OFFICIAL_ACTIVITY_EVIDENCE',

  // Non-proof / Not completed activity
  POSTER: 'POSTER',
  FLYER_OR_ADVERTISEMENT: 'FLYER_OR_ADVERTISEMENT',
  CAMPAIGN_MATERIAL: 'CAMPAIGN_MATERIAL',
  REGISTRATION_OR_TICKET: 'REGISTRATION_OR_TICKET',
  PAYMENT_RECEIPT: 'PAYMENT_RECEIPT',
  SCHEDULE_OR_TIMETABLE: 'SCHEDULE_OR_TIMETABLE',
  ACADEMIC_NOTES: 'ACADEMIC_NOTES',
  ID_CARD: 'ID_CARD',
  CERTIFICATE_TEMPLATE: 'CERTIFICATE_TEMPLATE',
  SCREENSHOT_OR_MEME: 'SCREENSHOT_OR_MEME',
  STUDENT_MISMATCH: 'STUDENT_MISMATCH',
  UNRELATED_DOCUMENT: 'UNRELATED_DOCUMENT',
  UNKNOWN: 'UNKNOWN'
};

export const EXTRACTION_SOURCES = {
  EMBEDDED_PDF_TEXT: 'EMBEDDED_PDF_TEXT',
  OCR_IMAGE: 'OCR_IMAGE',
  OCR_SCANNED_PDF: 'OCR_SCANNED_PDF',
  VISION_FALLBACK: 'VISION_FALLBACK',
  MANUAL: 'MANUAL'
};

